server:
  port: 8080
spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: "jdbc:postgresql://localhost:5432/RentACar"
    username: "postgres"
    password: "12345"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: update
  cloud:
    gateway:
      mvc:
        routes:
          - id: inventory-service
            uri: lb://inventory-service
            predicates:
              - Path=/api/**
          - id: customer-service
            uri: lb://customer-service
            predicates:
              - Path=/api/auth/**