spring:
  application:
    name: inventory-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: "jdbc:mysql://localhost:3306/rent-a-car"
    username: "root"
    password: "123456"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


